### ISSUE TITLE
Pas won't work after config tool used

### ISSUE THREAD

**Issue by Jimbojones2021** [mkopa/speeed#8]
I just built a bafang 750w new build out of the box. C500 display. Finished bike it was all working. Role programmed. Changed to 9 power settings and altered parameters now the Pas won't work but the throttle does. Tried altering the settings but nothing will get the Pas working I can find. Checked all the Hardware, it was working fine then wasn't after programming so it must be the programming. I just want to return to the factory settings now.

**Comment by mkopa** [comment]
@Jimbojones2021 Hi, I am very sorry to hear that you are having problems with your motor.
It is very important to save your original settings before modifications, so that you can restore them in the future.

I am giving you a file with default settings for BBS02 https://gist.githubusercontent.com/mkopa/8441ebaa6048cb9a4224c62667a56c06/raw/a54865429660f4ab0a794be26d2301c4275c31bd/bbs02.el

If this does not work, try uploading this file using the windows program "Bafang Configuration Tool".

Good luck and let us know the results.
